#!/bin/sh
HGBUNDLER=/opt/hgbundler

case "$1" in
  abort-deconfigure|abort-upgrade)
    ;;
  abort-remove)
  ;;
  configure)
    cd $HGBUNDLER
    if [ ! -f bin/buildout ]; then
       python bootstrap.py
    fi
    bin/buildout -n install eggs
    chmod 755 bin/*
    chmod 744 bin/buildout
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

