#!/bin/sh
HGBUNDLER=/opt/hgbundler

case "$1" in
  abort-deconfigure|abort-upgrade)
    ;;
  abort-remove)
  ;;
  configure)
    cd $HGBUNDLER
    if [ ! -f bin/buildout ]; then
       python offline-bootstrap.py -o
    fi
    # may have remnant of 'test' that's not multiplatform (zope.interface)
    rm -f $HGBUNDLER/.installed.cfg

    bin/buildout -o -N -c buildout-offline.cfg
    chmod 755 bin/*
    chmod 744 bin/buildout
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

