#!/bin/sh
HGBUNDLER=/opt/hgbundler

case "$1" in
  failed-upgrade)
  ;;
  remove|deconfigure)
     find $HGBUNDLER -name '*.pyc' -print0 | xargs -0 rm
     rm -rf $HGBUNDLER/develop-eggs $HGBUNDLER/parts 
     rm -rf $HGBUNDLER/bin
  ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

